### ISSUE TITLE
Display Seite ist komisch

### ISSUE THREAD

**Issue by j0hannr** [studio-arrenberg/quartiersdisplay-plugin#3]
![image](https://user-images.githubusercontent.com/52762073/210837481-8d0ec03a-635f-410b-bc7c-9f05908964b9.png)

**Comment by moritzwindmann** [comment]
Cache?
Bei mir sieht die anders aus...

![image](https://user-images.githubusercontent.com/41573605/210846832-a64954db-5524-4471-a785-f919f11a046c.png)

**Comment by j0hannr** [comment]
Sah bei mir am Handy heute mittag richtig aus, jetzt nicht mehr...

**Comment by j0hannr** [comment]
Cache wars!
